/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Irt0XGpPa3B
 */
import { Button } from "@/components/ui/button"

export function Atasama() {
  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900 flex flex-col items-center justify-center">
      <h1 className="text-4xl font-bold text-gray-800 dark:text-white mb-10">ATASAMA</h1>
      <div className="bg-white dark:bg-gray-800 shadow-lg rounded-lg p-6 w-full max-w-md">
        <h2 className="text-2xl font-semibold text-gray-700 dark:text-gray-200 mb-4">ROUTINE</h2>
        <div className="border-b border-gray-200 dark:border-gray-600 py-4">
          <h3 className="text-xl text-gray-600 dark:text-gray-400">Level 1</h3>
          <p className="text-gray-500 dark:text-gray-300">10 push-ups, 10 sit-ups, 10 squats, and a 1km run.</p>
        </div>
        <div className="border-b border-gray-200 dark:border-gray-600 py-4">
          <h3 className="text-xl text-gray-600 dark:text-gray-400">Level 2</h3>
          <p className="text-gray-500 dark:text-gray-300">20 push-ups, 20 sit-ups, 20 squats, and a 2km run.</p>
        </div>
        <div className="border-b border-gray-200 dark:border-gray-600 py-4">
          <h3 className="text-xl text-gray-600 dark:text-gray-400">Level 3</h3>
          <p className="text-gray-500 dark:text-gray-300">30 push-ups, 30 sit-ups, 30 squats, and a 3km run.</p>
        </div>
        {/* <Button className="mt-6 w-full h-12 text-white bg-blue-500 hover:bg-blue-600" variant="default">
          Start Workout
        </Button> */}
      </div>
    </div>
  )
}
